### ISSUE TITLE
Item slots

### ISSUE THREAD

**Issue by GreedyDragon** [Hokan-Ashir/SFGameDataEditor#41]
Hello Hokan!

Your editor is amazing and makes mod creating so much easier but i was wondering if you could "unlock" the units' item slots for example i would give the human recruit a shield and a 1h sword but i cant beacuse his left hand is locked and it would be nice if you also could do that with the chestplate , helm , pants slots aswell.
I know it will break the units skin but thats excatly what i want if possible. 

Thanks and keep up the good work!

**Comment by Hokan-Ashir** [comment]
Hi GreedyDragon,

Thanks for enjoining editor, I really appreciate that somebody occasionally bumping into it and finding it attractive =)

As for adding some slots to specific units - I'm afraid, but that's not possible. Amount of bytes that code each unit into Gamedata.cff file is strictly specified and can't be changed, even if somehow I'll add byte sequence that describes Tworstnik shield into Human's Recruit parameters, game will crush upon loading any save file or starting a game in any expansion. 

Tried already, same goes for any "additions" to file, like spell parameters, scroll parameters, hero spells etc.

As for giving ability to set chestplate instead of body skin, it's possible, but also same restriction goes for any unit - we can _change_ slot's fulfullment, but can't _add_ any new slots.
So if unit don't have leg's slot or head's slot, they can't be added by any means. Sorry =((
